
Neos:
  Flow:
    security:
      authentication:
        providers:
          FacebookOAuth2Provider:
            provider: Flowpack\OAuth2\Client\Provider\FacebookProvider
            providerOptions:
              authorizationEndpointUri: 'https://www.facebook.com/dialog/oauth'
              redirectionEndpointUri: 'https://www.yoursite.com/authentication/authenticate'
              tokenEndpointUri: 'https://graph.facebook.com/oauth/access_token'
              tokenEndpointClassName: Flowpack\OAuth2\Client\Endpoint\FacebookTokenEndpoint
              clientIdentifier: 123456-your-client-identifier
              clientSecret: '-add-your-client-secret-here-'
              responseType: code
              scopes:
                - email
              fields:
                - email
                - first_name
                - last_name
              partyCreation: true
              display: popup
          GoogleOAuth2Provider:
            provider: Flowpack\OAuth2\Client\Provider\GoogleProvider
            providerOptions:
              authorizationEndpointUri: 'https://accounts.google.com/o/oauth2/auth'
              redirectionEndpointUri: 'https://www.yoursite.com/authentication/authenticate'
              tokenEndpointUri: 'https://accounts.google.com/o/oauth2/token'
              tokenEndpointClassName: Flowpack\OAuth2\Client\Endpoint\GoogleTokenEndpoint
              clientIdentifier: 123456youridentifier.apps.googleusercontent.com
              clientSecret: '-add-your-client-secret-here-'
              responseType: code
              scopes:
                - 'https://www.googleapis.com/auth/userinfo.email'
                - 'https://www.googleapis.com/auth/userinfo.profile'
              partyCreation: true
              display: popup
